<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $words = [
            ['word' => 'arbre'],
            ['word' => 'avion'],
            ['word' => 'beaux'],
            ['word' => 'bleus'],
            ['word' => 'boire'],
            ['word' => 'brave'],
            ['word' => 'chien'],
            ['word' => 'clair'],
            ['word' => 'corps'],
            ['word' => 'croix'],
            ['word' => 'danse'],
            ['word' => 'dents'],
            ['word' => 'doute'],
            ['word' => 'eauxe'],
            ['word' => 'ennui'],
            ['word' => 'ferme'],
            ['word' => 'fille'],
            ['word' => 'flute'],
            ['word' => 'froid'],
            ['word' => 'fruit'],
            ['word' => 'gants'],
            ['word' => 'gazon'],
            ['word' => 'glace'],
            ['word' => 'grive'],
            ['word' => 'hiver'],
            ['word' => 'horas'],
            ['word' => 'image'],
            ['word' => 'jambe'],
            ['word' => 'jeudi'],
            ['word' => 'jouer'],
            ['word' => 'joute'],
            ['word' => 'jupes'],
            ['word' => 'lente'],
            ['word' => 'lourd'],
            ['word' => 'luire'],
            ['word' => 'lutte'],
            ['word' => 'mains'],
            ['word' => 'maman'],
            ['word' => 'mardi'],
            ['word' => 'mener'],
            ['word' => 'mètre'],
            ['word' => 'mielx'],
            ['word' => 'mouet'],
            ['word' => 'nager'],
            ['word' => 'noire'],
            ['word' => 'noter'],
            ['word' => 'noyau'],
            ['word' => 'ombre'],
            ['word' => 'orage'],
            ['word' => 'osier'],
            ['word' => 'pains'],
            ['word' => 'pluie'],
            ['word' => 'poids'],
            ['word' => 'pomme'],
            ['word' => 'poule'],
            ['word' => 'prier'],
            ['word' => 'quais'],
            ['word' => 'quint'],
            ['word' => 'races'],
            ['word' => 'ranch'],
            ['word' => 'rater'],
            ['word' => 'repos'],
            ['word' => 'retra'],
            ['word' => 'rivet'],
            ['word' => 'rouge'],
            ['word' => 'rural'],
            ['word' => 'sable'],
            ['word' => 'saint'],
            ['word' => 'seaux'],
            ['word' => 'seuil'],
            ['word' => 'sirop'],
            ['word' => 'singe'],
            ['word' => 'somme'],
            ['word' => 'songe'],
            ['word' => 'soupe'],
            ['word' => 'sport'],
            ['word' => 'sucre'],
            ['word' => 'table'],
            ['word' => 'talon'],
            ['word' => 'temps'],
            ['word' => 'terre'],
            ['word' => 'train'],
            ['word' => 'trame'],
            ['word' => 'tulle'],
            ['word' => 'union'],
            ['word' => 'utile'],
            ['word' => 'vague'],
            ['word' => 'valet'],
            ['word' => 'vente'],
            ['word' => 'vieux'],
            ['word' => 'ville'],
            ['word' => 'votre'],
            ['word' => 'wagon'],
            ['word' => 'zeste'],
            ['word' => 'zèbre'],
        ];

        DB::table('words')->insert($words);
    }
}
